### ISSUE TITLE
SegFault on Mac OS X

### ISSUE THREAD

**Issue by maennchen** [hansihe/rustler#113]
I have a SegFault which is only happening if the called code is executed using `rustler`.

I'm not sure on how to debug it, therefore I'm not sure if the problem is in the `rustler` or the `ex_openssl` project.

You can find the original issue here: jshmrtn/ex-openssl#1

Since this issue is time critical for me, I put a 250$ bounty on it:
https://www.bountysource.com/issues/52189211-segfault-on-macos

**Comment by hansihe** [comment]
This is strange. Since I don't have a mac, I can't really reproduce this locally very easy.

Could you print me the locals in stack frame 10 and 9? Should be something like this in lldb:

```lldb
frame 10
frame variable
```

**Comment by maennchen** [comment]
@hansihe

Frame Variables:
https://gist.github.com/maennchen/bbeb393debb0b9318c508357508f3977

**Comment by hansihe** [comment]
This is a really strange issue.

Workaround: https://gist.github.com/hansihe/0b3a20d16089769fa41625b5ba0584e8

**Comment by idyll** [comment]
I know what's going here @hansihe it's the `-flat_namespace` that was added previously to resolve #24. 

`-flat_namespace -undefined suppress` does not work anymore for macOS. When 10.13 was released Apple started shipping two SSL libs. BoringSSL and LibreSSL. BoringSSL is for their internal use and LibreSSL is what they want 3rd parties using. Typically we then all install OpenSSL via brew.

This situation confuses dynamic linking. The fix for Erlang is noted here: https://bugs.erlang.org/browse/ERL-439

Essentially, flat_namespace results in linking to Apple's BoringSSL which isn't even the standard implementation.

I am not familiar enough with rust to suggest a solution. But I know this is the issue.

**Comment by scrogson** [comment]
What I've been able to find is the follow options work best with macOS: 

```
-C link-arg=-undefined -C link-arg=dynamic_lookup
```

I've created #192 to address this.
