### ISSUE TITLE
Testing NIFs

### ISSUE THREAD

**Issue by NobbZ** [hansihe/Rustler#71]
What is the recommended way to test NIFs in rustler?

Does one implement tests in elixir that test the wrapping module? Does one write tests in rust? If the latter, how are they run?

**Comment by hansihe** [comment]
If you want to test the NIF as a whole, you need to implement your tests in Rust. This is because all functionality in rustler itself depends on functions exported by the BEAM.

If you want to test a more enterprise-logicy part of your NIF, it would probably make sense to write those tests with the Rust test framework.

If you have any more questions, feel free to ask them in the IRC or Slack channel.
