### ISSUE TITLE
Feature request: support for ports

### ISSUE THREAD

**Issue by YellowApple** [hansihe/rustler#78]
There's [some code already for decoding ETF terms within Rust programs](https://github.com/seriyps/rust-erl-ext), which I'm hoping to use with Rustler (mostly relegating Rustler to compiling crates for Rust-implemented Erlang ports) in order to implement a port or two for an Elixir app (using [this guide](http://www.theerlangelist.com/article/outside_elixir) as a reference, albeit with Rust instead of Ruby).  Would be nice to have a bit tighter integration on this front, though (in particular, being able to run something like `mix rustler.port.new` or `mix rustler.new --port` or something to generate the boilerplate like with NIF crates).

If I or someone else were to implement something like this for Rustler, would a PR be welcome?  Or is this out of scope for Rustler?

**Comment by scrogson** [comment]
Hi @YellowApple,

The scope of Rustler is for writing NIFs in Rust. Ports are not in scope for this library. You can however use something like [eetf](https://crates.io/crates/eetf) to encode/decode Erlang's External Term Format in Rust.

Ports just use pipes to communicate with an external program over stdin/stdout.

**Comment by YellowApple** [comment]
Alrighty then.  Will Rustler still work in this context just for automating crate building/management?  Or do they have to be tied to a NIF-implementing crate?

Also, thanks for the link to eetf; wasn't coming up in my search engine results, and looks to be a bit nicer than erl_ext (in terms of not having to deal with the prelude and actual term data separately).

**Comment by hansihe** [comment]
The mix compiler should work fine for building port drivers.

**Comment by cgregfreeman** [comment]
@hansihe 
By the mix compiler do you mean the code here: https://github.com/hansihe/rustler/blob/master/rustler_mix/lib/mix/tasks/compile.rustler.ex ?
If so, I could look into just modifying that code so that EETF has an equivalent, easy and automatic rust compilation for Elixir projects.
But, before I do that, what do you think of that idea?

**Comment by hansihe** [comment]
@cgregfreeman Yep, that's what I was taking about.

The code shouldn't even require any modification. You just write a crate with the kind of interface erlang expects from a port driver, and add it for compilation. You can then use the output dynamic library as a port driver.

**Comment by cgregfreeman** [comment]
@hansihe 
Thank you for the response. I've been struggling with this and I know this isn't a planned feature.

It _looks_  like the mix compiler has the right options to make a plain port, and not just a port driver. 

This may just require an easy way to tell Rustler to compile to binary and copy the binary to the native directory instead of a .so. I've been puzzling in the compiler.rustler.ex trying to figure out where to put the proper flag to enable what looks like a binary compiler target.
```Elixir
  defp make_base_command(:system), do: ["cargo", "rustc"]
  defp make_base_command({:bin, path}), do: [path, "rustc"]
```


Instead, I edited the cargo.toml of the rust file but the binary doesn't get placed in the native location by default. I was able to get a plain, basic port working with hard-linking the binary to the _build directory:

```elixir
defmodule PortExample do

  def test() do
    port = Port.open({:spawn, "_build/dev/rustler_crates/portexample/debug/portexample"}, [:binary])
    Port.info(port)

  end

end
```
I'm unsure if this is an easy fix by placing a flag somewhere or if it requires actually changing the compiler.rustler.ex file.

**Comment by hansihe** [comment]
@cgregfreeman I'm sorry for not responding earlier, I must have missed it.

The reason why the port executable itself is not found in the native location is because the mix compiler is hardcoded to copy files with a `.dll` or `.so` extension.

It would be nice to have the compiler be as general as possible, so I suppose we could add an option for this. Do you think that would be worth it?

**Comment by cgregfreeman** [comment]
@hansihe I think so.

The mix compiler you wrote is very handy for keeping the code in the right place. It already compiles binary targets if the .toml file has the [[bin]] name and path added manually, it just needs to copy the compiled binary to the priv/native folder where the .so's also end up.

Then it's up to the user to add their port code if they want or even have separate compiled binaries for whatever purpose.
